nyc_tlc:
  outputs:
    dev:
      account: shb16499.us-east-1
      database: nyc_tlc
      warehouse: COMPUTE_WH
      schema: public
      private_key_path: ../private_key_snowflake.rsa
      role: dbt_role
      threads: 1
      type: snowflake
      user: dbt
  target: dev