on:
  push:

concurrency: dbt_ci

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        PRIVATE_KEY: ${{ secrets.SNOWFLAKE_AUTH_PRIVATE_KEY }}

      steps:
        - uses: actions/checkout@v3
        - uses: ./.github/actions/setup

        - name: Run tests
          shell: bash
          run: inv run-integration-tests

