name: Run DBT

on:
  workflow-dispatch:

concurrency: dbt_dev

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        PRIVATE_KEY: ${{ secrets.SNOWFLAKE_AUTH_PRIVATE_KEY }}

      steps:
        - uses: actions/checkout@v3
        - uses: ./.github/actions/setup

        - name: Run DBT
          shell: bash
          run: inv run-dbt